server:
  port: 9000

spring:
  application:
    name: zabbix-integration

zabbix:
  server:
    ip: 127.0.0.1
    port: 8000
  api:
    key: my-secret-key
    feign:
      connectTimeout: 10000
      readTimeout: 60000