server:
  port: 9000

spring:
  application:
    name: zabbix-integration
  datasource:
    url: jdbc:postgresql://localhost:5432/db01
    username: postgres
    password: "qwerty$4"
    hikari:
      maximumPoolSize: 100
      minimumIdle: 10


zabbix:
  server:
    ip: 127.0.0.1
    port: 8000
  api:
    key: my-secret-key
    feign:
      connectTimeout: 10000
      readTimeout: 60000