server:
  port: 9000

spring:
  application:
    name: zabbix-integration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      appname: zabbix-integration

zabbix:
  server:
    ip: 127.0.0.1
    port: 8000
  api:
    key: my-secret-key
    feign:
      connectTimeout: 10000
      readTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: "info, health, beans, env"