eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      appname: metric-provider

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db01
    username: postgres
    password: "qwerty$4"
    hikari:
      maximumPoolSize: 100
      minimumIdle: 10